#!/bin/bash
if [ $# -ne 2 ]
then
    SCRIPT_NAME=`basename "$0"`
    echo "Usage:"
    echo "    $SCRIPT_NAME <old-version-number> <new-version-number>"
    echo "Example:"
    echo "    $SCRIPT_NAME 0.0.1 0.0.2-SNAPSHOT"
    exit 1   
fi
OLD_VERSION=$1
NEW_VERSION=$2
echo "Changing ACHE version from $OLD_VERSION to $NEW_VERSION..."
sed -i "s/version = '$OLD_VERSION'/version = '$NEW_VERSION'/" build.gradle
sed -i "s/    version: $OLD_VERSION/    version: $NEW_VERSION/" conda.recipe/meta.yaml
sed -i "s/    git_tag: $OLD_VERSION/    git_tag:: $NEW_VERSION/" conda.recipe/meta.yaml
echo "done."